version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: csu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csu_system_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - csu_mysql_data:/var/lib/mysql
    networks:
      - csu_net

  web:
    image: tomcat:10.1-jdk21-temurin
    container_name: csu_web
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./CSU_System/target/CSU_System.war:/usr/local/tomcat/webapps/CSU_System.war
    networks:
      - csu_net

  frontend:
    image: node:20
    platform: linux/amd64
    container_name: csu_frontend
    working_dir: /app
    volumes:
      - ./csu-system-frontend:/app
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start -- --host=0.0.0.0"
    depends_on:
      - web
    networks:
      - csu_net

volumes:
  csu_mysql_data:

networks:
  csu_net:
